In [4]:
import numpy as np

In [11]:
values = [1,2,3,4,5]
values = np.array(values) + 5
values

array([ 6,  7,  8,  9, 10])

In [12]:
x = np.multiply(values, 5)
x

array([30, 35, 40, 45, 50])

In [13]:
x = values * 5
x

array([30, 35, 40, 45, 50])

In [23]:
a = np.array([[1,3],[5,7]])
b = np.array([[2,4],[6,8]])
a+b

array([[ 3,  7],
       [11, 15]])